export const LOCAL_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_LOCAL_CONTRACT_ADDRESS
export const MUMBAI_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_MUMBAI_CONTRACT_ADDRESS
export const GANACHE_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_GANACHE_CONTRACT_ADDRESS

export const WALLET_CONNECT_PROJECT = process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT
export const ENVIROMENT = process.env.NEXT_PUBLIC_ENVIROMENT;